"""Comments model added

Revision ID: 7279fb38148c
Revises: 73b9f0054df7
Create Date: 2020-04-17 19:09:43.203295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7279fb38148c'
down_revision = '73b9f0054df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advert_id'], ['advert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_advert_id'), 'comment', ['advert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_advert_id'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
