"""fixed 'price' field in adverts table

Revision ID: c68e835fdee0
Revises: d22fc235bc5e
Create Date: 2020-04-28 22:36:01.669291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68e835fdee0'
down_revision = 'd22fc235bc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advert', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_advert_url'), ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advert', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_advert_url'), type_='unique')

    # ### end Alembic commands ###
