"""added and fixed fields in adverts table

Revision ID: d22fc235bc5e
Revises: 6da05acf1866
Create Date: 2020-04-28 19:47:13.260067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22fc235bc5e'
down_revision = '6da05acf1866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fail_check', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('text')
        batch_op.drop_column('adress')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('advert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('foto')
        batch_op.drop_column('fail_check')
        batch_op.drop_column('description')
        batch_op.drop_column('company')
        batch_op.drop_column('closed')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
